name: DealHive

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@master
        with:
          version: 18.x

      - name: yarn install.
        run: yarn

      - name: check build.
        run: yarn build
